"""Public contracts for Orchestune's repository consistency kernel."""

from orchestune.consistency.contracts import (
    Invariant,
    Observer,
    RepairExecutor,
    RepairPlanner,
)
from orchestune.consistency.engine import ConsistencyEngine
from orchestune.consistency.models import (
    ConsistencyFinding,
    ConsistencyReport,
    ConsistencyScope,
    DesiredFact,
    DesiredRepositoryState,
    Evidence,
    FactValue,
    FindingSeverity,
    IntentStatus,
    Observation,
    ObservationCertainty,
    ObservedRepositoryState,
    Repairability,
    RepairCommand,
    RepairResult,
    RepairStatus,
    ScopedObservations,
    StateChanged,
    TransitionIntent,
)

__all__ = [
    "ConsistencyEngine",
    "ConsistencyFinding",
    "ConsistencyReport",
    "ConsistencyScope",
    "DesiredFact",
    "DesiredRepositoryState",
    "Evidence",
    "FactValue",
    "FindingSeverity",
    "IntentStatus",
    "Invariant",
    "Observation",
    "ObservationCertainty",
    "ObservedRepositoryState",
    "Observer",
    "RepairCommand",
    "RepairExecutor",
    "RepairPlanner",
    "RepairResult",
    "RepairStatus",
    "Repairability",
    "ScopedObservations",
    "StateChanged",
    "TransitionIntent",
]
